import { useEffect, useState } from "react";
import { Check, ChevronLeft, Copy, Gem, LoaderCircle, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { formatMoney, formatOunces, goldPrice } from "@/data/mock-data";
import { useCente } from "@/state/cente-context";

export function ActionFlow({ kind, open, onOpenChange, presetCurrency = "NGN" }) {
  const { balances, gold, completeAction, verified, verify, pinSet, setupPin } = useCente();
  const [step, setStep] = useState("form");
  const [currency, setCurrency] = useState(presetCurrency);
  const [amount, setAmount] = useState("");
  const [pin, setPin] = useState("");
  const [bvn, setBvn] = useState("");
  const [error, setError] = useState("");
  const [copied, setCopied] = useState(false);
  const [fundingMethod, setFundingMethod] = useState("card");
  useEffect(() => { if (open) { setCurrency(presetCurrency); setFundingMethod("card"); } }, [open, presetCurrency]);
  const numeric = Number(amount) || 0, isGoldSell = kind === "gold-sell", isFund = kind === "fund";
  const title = { fund: "Fund Wallet", save: "Add to Safevest", withdraw: "Withdraw Savings", "gold-buy": "Buy Safevest Gold", "gold-sell": "Sell Gold" }[kind] ?? "Transaction";
  const estimate = kind === "gold-buy" ? numeric / goldPrice[currency] : (kind === "gold-sell" ? numeric * goldPrice[currency] * .995 : numeric);
  const close = (value) => { onOpenChange(value); if (!value) setTimeout(() => { setStep("form"); setAmount(""); setPin(""); setError(""); setFundingMethod("card"); }, 200); };
  const continueFlow = () => { setError(""); if (numeric <= 0) return setError("Enter an amount greater than zero."); if (isGoldSell && numeric > gold.ounces) return setError("You do not have enough gold to sell this quantity."); if (!["fund","withdraw","gold-sell"].includes(kind) && numeric > balances[currency]) return setError("Your available balance is too low for this transaction."); if (!verified && ["save","withdraw","gold-buy","gold-sell"].includes(kind)) return setStep("kyc"); setStep("review"); };
  const submit = () => { if (isFund) { completeAction({ type: kind, amount: numeric, currency }); return setStep("success"); } if (pin.length !== 4) return setError("Enter your 4-digit security PIN."); if (!pinSet) setupPin(); setStep("loading"); setTimeout(() => { completeAction({ type: kind, amount: numeric, currency, product: currency }); setStep("success"); }, 700); };
  const usdtAddress = "0x7a2F8e4D9c3B1a6E5f8D2c4B7e9A3f1C6d0E8b5F";
  const reviewFields = isFund && currency === "USD" ? [["Method", fundingMethod === "card" ? "Card / Fiat (Ramp)" : "Stablecoin (USDT/USDC)"], ["Estimated fee", fundingMethod === "card" ? formatMoney(numeric * 0.015, "USD") : formatMoney(0, "USD")]] : (isFund ? [["Destination", "CENTE NGN Collections"]] : [["Estimated fee", formatMoney(numeric * 0.005, currency)]]);
  return <Sheet open={open} onOpenChange={close}><SheetContent side="bottom" className="mx-auto max-h-[94vh] overflow-y-auto rounded-t-2xl border-border bg-background p-0 sm:bottom-4 sm:max-w-xl sm:rounded-2xl"><div className="sticky top-0 z-10 border-b border-border bg-background px-5 py-5"><SheetHeader><SheetTitle>{!["form","success"].includes(step) && <button onClick={() => setStep("form")} className="mr-2 align-middle" aria-label="Back"><ChevronLeft className="inline size-5" /></button>}{title}</SheetTitle><SheetDescription>Frontend prototype · No real funds will move</SheetDescription></SheetHeader></div><div className="p-5 pb-8">
    {step === "form" && <div className="space-y-5"><div><label className="form-label">{isGoldSell ? "Payout currency" : "Funding currency"}</label><div className="flex gap-2">{["USD","NGN"].map((c) => <Button key={c} variant={currency === c ? "default" : "outline"} onClick={() => { setCurrency(c); setFundingMethod("card"); }}>{c}</Button>)}</div></div>
      {isFund && currency === "USD" && <><div><label className="form-label">Funding Method</label><div className="grid grid-cols-2 gap-2">
        <button className={`choice ${fundingMethod === "card" ? "choice-active" : ""}`} onClick={() => setFundingMethod("card")}>💳 Buy with Card</button>
        <button className={`choice ${fundingMethod === "stablecoin" ? "choice-active" : ""}`} onClick={() => setFundingMethod("stablecoin")}>🪙 USDT/USDC</button>
      </div></div>
      {fundingMethod === "card" && <><div className="rounded-lg border border-primary/30 bg-primary/8 p-4 text-center"><p className="text-sm font-semibold">Payment Provider</p><p className="mt-2 text-xs text-muted-foreground">You will be redirected to a secure payment provider to complete your purchase.</p><Button variant="outline" className="mt-4 w-full" onClick={() => setError("Redirecting to payment provider... (demo)")}><span>Open Ramp Provider</span></Button></div></>}
      {fundingMethod === "stablecoin" && <><div className="rounded-lg border border-border bg-secondary/50 p-4 text-sm"><div className="flex justify-between items-center"><span className="text-muted-foreground">Send USDT/USDC to:</span><Button variant="ghost" size="sm" onClick={async () => { await navigator.clipboard.writeText(usdtAddress); setCopied(true); }}><Copy />{copied ? "Copied" : "Copy"}</Button></div><p className="mt-3 break-all font-mono text-xs">{usdtAddress}</p><p className="mt-2 text-xs text-muted-foreground">Any ERC-20 stablecoin (USDT or USDC) on Ethereum network. Minimum deposit: 10 USD equivalent.</p></div></>}
      {fundingMethod === "card" && <div className="mt-3 rounded-lg bg-warning/8 border border-warning/20 p-3 text-xs text-warning"><strong>Note:</strong> Card purchases are processed instantly. A 1.5% processing fee applies (mock).</div>}
      {fundingMethod === "stablecoin" && <div className="mt-3 rounded-lg bg-success/8 border border-success/20 p-3 text-xs text-success"><strong>Note:</strong> Stablecoin deposits are confirmed after 3 network confirmations (mock).</div>}
      </>}
      {isFund && currency === "NGN" && <><div className="rounded-lg border border-primary/30 bg-primary/8 p-4"><p className="text-sm font-semibold">Transfer money to this account</p><div className="mt-4 space-y-3 text-sm">{[["Bank name","CENTE Partner Bank"],["Account name","CENTE NGN Collections"],["Account number","8042196501"]].map(([k,v]) => <div key={k} className="flex justify-between gap-4"><span className="text-muted-foreground">{k}</span><strong className="text-right">{v}</strong></div>)}</div><Button variant="outline" className="mt-4 w-full" onClick={async () => { await navigator.clipboard.writeText("8042196501"); setCopied(true); }}><Copy />{copied ? "Copied" : "Copy account number"}</Button></div><ol className="space-y-2 text-sm text-muted-foreground"><li><strong className="text-foreground">1.</strong> Transfer money to the displayed account.</li><li><strong className="text-foreground">2.</strong> Enter the amount you sent.</li><li><strong className="text-foreground">3.</strong> Confirm the transfer.</li></ol></>}
      <div><label className="form-label">{isGoldSell ? "Gold weight (OZ)" : "Amount sent"}</label><div className="amount-field"><span>{isGoldSell ? "OZ" : currency === "USD" ? "$" : "₦"}</span><Input autoFocus={!isFund} inputMode="decimal" value={amount} onChange={(e) => setAmount(e.target.value.replace(/[^0-9.]/g,""))} placeholder="0.00" /></div><p className="mt-2 text-xs text-muted-foreground">{isFund ? (currency === "USD" && fundingMethod === "card" ? "Enter the amount you are spending (includes fees)" : `Enter the exact ${currency} amount deposited`) : `Available: ${isGoldSell ? formatOunces(gold.ounces) : formatMoney(balances[currency],currency)}`}</p></div>
      {kind.startsWith("gold") && numeric > 0 && <div className="rounded-lg border border-border bg-secondary/50 p-4 text-sm"><div className="flex justify-between"><span className="text-muted-foreground">Estimated {isGoldSell ? "payout" : "gold weight"}</span><strong>{isGoldSell ? formatMoney(estimate,currency) : formatOunces(estimate)}</strong></div><div className="mt-2 flex justify-between text-xs text-muted-foreground"><span>Mock gold value</span><span>{formatMoney(goldPrice[currency],currency)} / OZ</span></div></div>}
      {kind === "gold-buy" && <div className="flex gap-3 rounded-lg bg-primary/8 p-4 text-xs text-muted-foreground"><Gem className="size-4 shrink-0 text-primary" />Gold pricing is simulated and is not a live commodity price.</div>}{error && <p className="text-sm text-destructive">{error}</p>}<Button size="lg" className="w-full" onClick={continueFlow}>{isFund ? "Review transfer" : "Continue"}</Button>{isFund && <Button variant="ghost" className="w-full" onClick={() => close(false)}>Cancel</Button>}</div>}
    {step === "kyc" && <div className="space-y-5"><span className="grid size-14 place-items-center rounded-full bg-primary/12 text-primary"><ShieldCheck /></span><div><h3 className="text-xl font-semibold">BVN verification</h3><p className="mt-1 text-sm text-muted-foreground">Nigerian users complete a lightweight mock BVN check before regulated actions.</p></div><Input className="h-12" inputMode="numeric" maxLength={11} value={bvn} onChange={(e) => setBvn(e.target.value.replace(/\D/g,""))} placeholder="Enter 11-digit BVN" /><Button className="w-full" size="lg" disabled={bvn.length !== 11} onClick={() => { verify(); setStep("review"); }}>Verify and continue</Button><p className="text-center text-xs text-muted-foreground">Mock verification only. No identity service is connected.</p></div>}
    {step === "review" && <div className="space-y-5"><h3 className="font-display text-2xl">{isFund ? "Confirm your transfer" : "Review transaction"}</h3><div className="divide-y divide-border rounded-lg border border-border">{[[isGoldSell ? "Gold weight" : "Amount",isGoldSell ? formatOunces(numeric) : formatMoney(numeric,currency)],["Currency",currency],["Action",title],...reviewFields].map(([k,v]) => <div key={k} className="flex justify-between gap-4 p-4 text-sm"><span className="text-muted-foreground">{k}</span><strong className="text-right">{v}</strong></div>)}</div><p className="rounded-lg bg-secondary p-4 text-xs text-muted-foreground">{isFund ? "Confirm only after sending the exact amount. This prototype updates your mock balance immediately." : "Review these mock details before continuing."}</p><Button size="lg" className="w-full" onClick={() => isFund ? submit() : setStep("pin")}>{isFund ? "I've Sent This" : "Confirm transaction"}</Button><Button variant="ghost" className="w-full" onClick={() => close(false)}>Cancel</Button></div>}
    {step === "pin" && <div className="space-y-5 text-center"><div><h3 className="text-xl font-semibold">{pinSet ? "Enter security PIN" : "Create security PIN"}</h3><p className="text-sm text-muted-foreground">Use four digits to protect sensitive actions.</p></div><div className="flex justify-center gap-3">{[0,1,2,3].map((i) => <span key={i} className={`size-3 rounded-full border ${pin.length > i ? "border-primary bg-primary" : "border-border"}`} />)}</div><div className="mx-auto grid max-w-xs grid-cols-3 gap-2">{[1,2,3,4,5,6,7,8,9,"",0,"⌫"].map((n,i) => <button key={i} disabled={n === ""} onClick={() => n === "⌫" ? setPin((p) => p.slice(0,-1)) : setPin((p) => p.length < 4 ? p+String(n) : p)} className="keypad">{n}</button>)}</div>{error && <p className="text-sm text-destructive">{error}</p>}<Button size="lg" className="w-full" onClick={submit}>Authorize</Button></div>}
    {step === "loading" && <div className="grid min-h-72 place-items-center text-center"><div><LoaderCircle className="mx-auto size-10 animate-spin text-primary" /><p className="mt-4 font-medium">Processing securely…</p></div></div>}
    {step === "success" && <div className="grid min-h-72 place-items-center text-center"><div><span className="mx-auto grid size-16 place-items-center rounded-full bg-success/12 text-success"><Check className="size-8" /></span><h3 className="mt-5 font-display text-3xl">{isFund ? "Transfer confirmed" : "Transaction complete"}</h3><p className="mt-2 text-sm text-muted-foreground">Your mock balance and activity have been updated.</p><Button className="mt-7 w-full" size="lg" onClick={() => close(false)}>Done</Button></div></div>}
  </div></SheetContent></Sheet>;
}
