import { Link } from "@tanstack/react-router";
import { ArrowDownToLine, ArrowRight, ArrowUpRight, Eye, EyeOff, Gem, Landmark, RefreshCw, Send, TrendingUp, WalletCards } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { ActionFlow, type FlowKind } from "./action-flow";
import { formatMoney, safevestProducts, type Currency } from "@/data/mock-data";
import { useCente } from "@/state/cente-context";
import { MiniChart, TransactionRow } from "./ui";
import { WelcomeGate } from "./welcome-gate";

const actions = [
  { label:"Fund wallet", icon:ArrowDownToLine, kind:"fund" }, { label:"Send money",icon:Send,kind:"send" }, { label:"Safevest USD",icon:Landmark,kind:"save",currency:"USD" }, { label:"Safevest NGN",icon:WalletCards,kind:"save",currency:"NGN" }, { label:"Safevest Gold",icon:Gem,kind:"gold-buy",currency:"NGN" }, { label:"USDT swap",icon:RefreshCw,kind:"swap",currency:"USDT" },
] as const;

export function HomePage() {
  const { balances, hidden, toggleHidden, transactions, gold }=useCente(); const [currency,setCurrency]=useState<Currency>("NGN"); const [flow,setFlow]=useState<{kind:FlowKind;currency:Currency}|null>(null);
  return <><WelcomeGate/><section><div className="mb-5"><p className="text-sm text-muted-foreground">Good evening, Samuel</p><h1 className="font-display text-3xl font-semibold">Your wealth, thoughtfully managed.</h1></div><div className="grid gap-5 xl:grid-cols-[1.3fr_.7fr]">
    <div className="balance-card relative min-h-72 overflow-hidden rounded-xl p-5 sm:p-7"><div className="relative z-10"><div className="grid grid-cols-[minmax(0,1fr)_auto] gap-3"><div className="min-w-0"><p className="text-xs text-primary-foreground/65">Total balance · {currency}</p><div className="mt-2 flex min-w-0 items-center gap-3"><p className="truncate text-3xl font-semibold text-primary-foreground sm:text-4xl">{hidden?"••••••":currency==="GOLD"?`${gold.grams.toFixed(3)}g`:formatMoney(balances[currency],currency)}</p><button onClick={toggleHidden} className="grid size-11 shrink-0 place-items-center rounded-full bg-background/10 text-primary-foreground" aria-label="Toggle balance">{hidden?<Eye/>:<EyeOff/>}</button></div><p className="mt-2 text-xs text-primary-foreground/55">Wallet ID · CT-8042-1965</p></div><TrendingUp className="size-6 text-primary"/></div><div className="mt-12 flex gap-2 overflow-x-auto pb-1">{(["NGN","USD","USDT","GOLD"] as Currency[]).map(c=><button key={c} onClick={()=>setCurrency(c)} className={`min-h-11 min-w-17 rounded-lg border px-3 text-xs font-semibold ${currency===c?"border-primary bg-primary text-primary-foreground":"border-primary-foreground/20 bg-primary-foreground/5 text-primary-foreground/70"}`}>{c}</button>)}</div><div className="mt-5 flex items-center justify-between"><span className="text-xs text-primary-foreground/55">Mock prices · updated moments ago</span><span className="text-xs font-semibold text-success">+4.8% this month</span></div></div></div>
    <div className="panel p-5"><div className="flex justify-between"><div><p className="text-xs text-muted-foreground">Portfolio growth</p><p className="mt-1 text-xl font-semibold">+₦184,220</p></div><span className="text-xs text-success">+8.2%</span></div><MiniChart/><div className="grid grid-cols-2 gap-3 border-t border-border pt-4 text-xs"><div><span className="text-muted-foreground">Invested</span><strong className="mt-1 block">₦4.92m</strong></div><div><span className="text-muted-foreground">Returns</span><strong className="mt-1 block text-success">₦392k</strong></div></div></div>
  </div></section>
  <section className="mt-8"><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-semibold">Quick actions</h2><span className="text-xs text-muted-foreground">Demo mode</span></div><div className="grid grid-cols-3 gap-3 sm:grid-cols-6">{actions.map(a=>{const Icon=a.icon;return <button key={a.label} onClick={()=>setFlow({kind:a.kind,currency:(a.currency??"NGN") as Currency})} className="panel group flex min-h-25 flex-col items-center justify-center gap-2 p-3 text-center transition hover:border-primary/40 hover:-translate-y-0.5"><span className="grid size-10 place-items-center rounded-lg bg-primary/10 text-primary"><Icon className="size-4.5"/></span><span className="text-[11px] font-semibold leading-tight">{a.label}</span></button>})}</div></section>
  <section className="mt-8 grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><div className="panel p-5"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold">Recent activity</h2><Link to="/transactions" className="flex min-h-11 items-center gap-1 text-xs font-semibold text-primary">View all <ArrowRight className="size-4"/></Link></div><div>{transactions.slice(0,4).map(tx=><TransactionRow key={tx.id} tx={tx}/>)}</div></div><div className="space-y-3"><div className="flex justify-between"><h2 className="text-lg font-semibold">Safevest</h2><Link to="/wealth" className="text-xs font-semibold text-primary">Explore</Link></div>{safevestProducts.map(p=><Link key={p.id} to="/wealth" className="panel grid min-h-24 grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-3 p-4"><span className="grid size-11 place-items-center rounded-lg bg-secondary text-primary"><Landmark className="size-5"/></span><span className="min-w-0"><span className="block text-sm font-semibold">{p.name}</span><span className="block text-xs text-muted-foreground">{p.rate}</span></span><span className="text-right text-sm font-semibold">{formatMoney(p.balance,p.currency as Currency)}<ArrowUpRight className="ml-auto mt-1 size-3 text-success"/></span></Link>)}</div></section>
  <ActionFlow kind={flow?.kind??"fund"} presetCurrency={flow?.currency} open={Boolean(flow)} onOpenChange={v=>!v&&setFlow(null)}/></>;
}