import { Link } from "react-router-dom";
import { ArrowDownToLine, ArrowRight, Eye, EyeOff, Gem, Landmark, ReceiptText, Send, WalletCards } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { ActionFlow } from "./action-flow";
import { formatMoney, rates, safevestProducts } from "@/data/mock-data";
import { useCente } from "@/state/cente-context";
import { TransactionRow } from "./ui";
import { WelcomeGate } from "./welcome-gate";

const actions = [
  { label: "Fund Wallet", icon: ArrowDownToLine, kind: "fund" }, { label: "Send Money", icon: Send, to: "/send" }, { label: "Transactions", icon: ReceiptText, to: "/transactions" },
  { label: "Safevest USD", icon: Landmark, to: "/wealth?product=USD" }, { label: "Safevest NGN", icon: WalletCards, to: "/wealth?product=NGN" }, { label: "Safevest Gold", icon: Gem, to: "/wealth?product=GOLD" },
];
export function HomePage() {
  const { balances, hidden, toggleHidden, transactions } = useCente(); const [currency, setCurrency] = useState("NGN"); const [flow, setFlow] = useState(null);
  const totalNgn = balances.NGN + balances.USD * rates.NGN_USD;
  return <><WelcomeGate /><section><div className="mb-5"><p className="text-sm text-muted-foreground">Good afternoon, Samuel</p><h1 className="font-display text-3xl font-semibold">Your wealth, thoughtfully managed.</h1></div>
    <div className="grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><div className="balance-card relative min-h-76 overflow-hidden rounded-xl p-5 sm:p-7"><div className="relative z-10"><div className="flex items-start justify-between gap-3"><div><p className="text-xs text-primary-foreground/65">Total wallet balance</p><p className="mt-2 text-3xl font-semibold text-primary-foreground sm:text-4xl">{hidden ? "••••••" : formatMoney(totalNgn)}</p><p className="mt-2 text-xs text-primary-foreground/60">Estimated across USD and NGN · Mock rate</p></div><Button variant="ghost" size="icon" onClick={toggleHidden} className="bg-background/10 text-primary-foreground hover:bg-background/20" aria-label="Toggle balance">{hidden ? <Eye /> : <EyeOff />}</Button></div>
      <div className="mt-9 flex gap-2">{["USD", "NGN"].map((c) => <Button key={c} variant="ghost" onClick={() => setCurrency(c)} className={currency === c ? "border border-primary-foreground/30 bg-primary-foreground/16 text-primary-foreground" : "border border-primary-foreground/15 text-primary-foreground/70"}>{c} Wallet</Button>)}</div>
      <div className="mt-4 flex items-end justify-between gap-4"><div><p className="text-xs text-primary-foreground/60">{currency} available</p><p className="mt-1 text-xl font-semibold text-primary-foreground">{hidden ? "••••" : formatMoney(balances[currency], currency)}</p></div><Button onClick={() => setFlow({ kind: "fund", currency })}><ArrowDownToLine />Fund Wallet</Button></div></div></div>
      <div className="panel p-5"><p className="text-xs text-muted-foreground">Wallets</p><div className="mt-4 space-y-3">{["USD", "NGN"].map((c) => <button key={c} onClick={() => setCurrency(c)} className="grid min-h-18 w-full grid-cols-[auto_1fr_auto] items-center gap-3 rounded-lg border border-border p-3 text-left"><span className="grid size-10 place-items-center rounded-lg bg-secondary font-bold text-primary">{c === "USD" ? "$" : "₦"}</span><span><strong className="block text-sm">{c} Wallet</strong><small className="text-muted-foreground">Available balance</small></span><strong className="text-sm">{hidden ? "••••" : formatMoney(balances[c], c)}</strong></button>)}</div></div></div></section>
    <section className="mt-8"><h2 className="mb-4 text-lg font-semibold">Quick Actions</h2><div className="grid grid-cols-3 gap-3 sm:grid-cols-6">{actions.map((a) => { const Icon = a.icon; const content = <><span className="grid size-10 place-items-center rounded-lg bg-primary/10 text-primary"><Icon className="size-4.5" /></span><span className="text-[11px] font-semibold leading-tight">{a.label}</span></>; return a.to ? <Link key={a.label} to={a.to} className="panel flex min-h-25 flex-col items-center justify-center gap-2 p-3 text-center transition hover:border-primary/40">{content}</Link> : <button key={a.label} onClick={() => setFlow({ kind: a.kind, currency })} className="panel flex min-h-25 flex-col items-center justify-center gap-2 p-3 text-center">{content}</button>; })}</div></section>
    <section className="mt-8 grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><div className="panel p-5"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold">Recent activity</h2><Link to="/transactions" className="flex min-h-11 items-center gap-1 text-xs font-semibold text-primary">View all <ArrowRight className="size-4" /></Link></div>{transactions.slice(0,4).map((tx) => <TransactionRow key={tx.id} tx={tx} />)}</div><div className="space-y-3"><h2 className="text-lg font-semibold">Safevest</h2>{safevestProducts.map((p) => <Link key={p.id} to={`/wealth?product=${p.id}`} className="panel grid min-h-24 grid-cols-[auto_1fr_auto] items-center gap-3 p-4"><span className="grid size-11 place-items-center rounded-lg bg-secondary text-primary"><Landmark /></span><span><strong className="block text-sm">{p.name}</strong><small className="text-muted-foreground">{p.rate}</small></span><strong>{formatMoney(p.balance,p.currency)}</strong></Link>)}</div></section>
    <ActionFlow kind={flow?.kind ?? "fund"} presetCurrency={flow?.currency} open={Boolean(flow)} onOpenChange={(v) => !v && setFlow(null)} /></>;
}
