import { useState } from "react";
import { Check, ChevronLeft, Send } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { PageTitle } from "./ui";
import { formatMoney, rates } from "@/data/mock-data";
import { useCente } from "@/state/cente-context";

export default function SendPage() {
  const { balances, completeAction, verified, verify } = useCente(); const [step,setStep]=useState("details"), [source,setSource]=useState("USD"), [destination,setDestination]=useState("USD"), [method,setMethod]=useState("USD Local (ACH)"), [amount,setAmount]=useState(""), [recipient,setRecipient]=useState({name:"",bank:"",account:"",routing:"",address:""}), [bvn,setBvn]=useState(""), [error,setError]=useState(""); const numeric=Number(amount)||0;
  const methods = destination === "USD" ? ["USD Local (ACH)","International Wire / SWIFT"] : ["NGN Local Bank Transfer"]; const received = source === destination ? numeric : source === "NGN" ? numeric/rates.NGN_USD*.995 : numeric*rates.NGN_USD*.995;
  const setField=(key,value)=>setRecipient((r)=>({...r,[key]:value})); const next=()=>{setError(""); if(numeric<=0)return setError("Enter an amount greater than zero."); if(numeric>balances[source])return setError("Your available balance is too low."); if(!recipient.name||!recipient.bank||!recipient.account)return setError("Complete the recipient details."); if(!verified)return setStep("verify"); setStep("review");}; const submit=()=>{completeAction({type:"send",amount:numeric,currency:source,recipient:recipient.name,payoutMethod:method});setStep("success")};
  return <><PageTitle eyebrow="Payments" title="Send Money" copy="Send from your USD or NGN wallet using realistic mock payout details."/><div className="mx-auto max-w-3xl panel p-5 sm:p-7">{step!=="details"&&step!=="success"&&<Button variant="ghost" onClick={()=>setStep("details")} className="mb-4"><ChevronLeft/>Back</Button>}
    {step==="details"&&<div className="space-y-6"><div className="grid gap-4 sm:grid-cols-2"><div><label className="form-label">Source Wallet</label><select className="field" value={source} onChange={(e)=>setSource(e.target.value)}><option value="USD">USD Wallet</option><option value="NGN">NGN Wallet</option></select><p className="mt-2 text-xs text-muted-foreground">Available {formatMoney(balances[source],source)}</p></div><div><label className="form-label">Destination Currency</label><select className="field" value={destination} onChange={(e)=>{const v=e.target.value;setDestination(v);setMethod(v==="USD"?"USD Local (ACH)":"NGN Local Bank Transfer")}}><option>USD</option><option>NGN</option></select></div></div><div><label className="form-label">Payout Method</label><div className="grid gap-2 sm:grid-cols-2">{methods.map((m)=><button key={m} className={method===m?"choice-active":"choice"} onClick={()=>setMethod(m)}>{m}</button>)}</div></div><div><label className="form-label">Amount</label><div className="amount-field"><span>{source==="USD"?"$":"₦"}</span><Input inputMode="decimal" value={amount} onChange={(e)=>setAmount(e.target.value.replace(/[^0-9.]/g,""))} placeholder="0.00"/></div>{source!==destination&&numeric>0&&<p className="mt-2 text-xs text-muted-foreground">Estimated recipient amount: {formatMoney(received,destination)} · Mock rate, including 0.5% demo fee</p>}</div><div className="border-t border-border pt-6"><h2 className="font-semibold">Recipient Details</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><Input placeholder="Recipient full name" value={recipient.name} onChange={(e)=>setField("name",e.target.value)}/><Input placeholder="Bank name" value={recipient.bank} onChange={(e)=>setField("bank",e.target.value)}/><Input placeholder="Account number" value={recipient.account} onChange={(e)=>setField("account",e.target.value)}/><Input placeholder={method.includes("SWIFT")?"SWIFT / BIC code":"Routing number"} value={recipient.routing} onChange={(e)=>setField("routing",e.target.value)}/>{method.includes("SWIFT")&&<Input className="sm:col-span-2" placeholder="Recipient bank address" value={recipient.address} onChange={(e)=>setField("address",e.target.value)}/>}</div></div>{error&&<p className="text-sm text-destructive">{error}</p>}<Button size="lg" className="w-full" onClick={next}>Review Transfer</Button></div>}
    {step==="verify"&&<div className="space-y-5"><h2 className="font-display text-2xl">BVN verification</h2><p className="text-sm text-muted-foreground">Complete this frontend-only mock check to continue.</p><Input inputMode="numeric" maxLength={11} placeholder="Enter 11-digit BVN" value={bvn} onChange={(e)=>setBvn(e.target.value.replace(/\D/g,""))}/><Button disabled={bvn.length!==11} className="w-full" onClick={()=>{verify();setStep("review")}}>Verify and Continue</Button></div>}
    {step==="review"&&<div className="space-y-5"><h2 className="font-display text-2xl">Review Transfer</h2><div className="divide-y divide-border rounded-lg border">{[["Send",formatMoney(numeric,source)],["Recipient gets",formatMoney(received,destination)],["Recipient",recipient.name],["Payout method",method],["Bank",recipient.bank],["Account",recipient.account]].map(([k,v])=><div key={k} className="flex justify-between gap-4 p-4 text-sm"><span className="text-muted-foreground">{k}</span><strong className="text-right">{v}</strong></div>)}</div><p className="rounded-lg bg-secondary p-4 text-xs text-muted-foreground">This is a mock transfer. No bank instruction or real payment is created.</p><Button size="lg" className="w-full" onClick={submit}><Send/>Confirm and Send</Button></div>}
    {step==="success"&&<div className="grid min-h-80 place-items-center text-center"><div><span className="mx-auto grid size-16 place-items-center rounded-full bg-success/12 text-success"><Check/></span><h2 className="mt-5 font-display text-3xl">Transfer complete</h2><p className="mt-2 text-sm text-muted-foreground">The mock transaction is now in your activity.</p><Button className="mt-6" onClick={()=>{setStep("details");setAmount("");setRecipient({name:"",bank:"",account:"",routing:"",address:""})}}>Send Another</Button></div></div>}</div></>;
}
